name: test-automatico

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  pruebas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: instalar-dependencias
        run: npm install
      - name: ejecutar-pruebas
        run: npm test
